# Generated by Django 4.2.1 on 2023-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_kk",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_sn",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
