# Generated by Django 4.2.1 on 2023-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0002_alter_item_item_it_alter_item_item_kk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("barcode", models.IntegerField(blank=True, null=True)),
                ("modified", models.DateField(auto_now=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_return", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
