# Generated by Django 4.2.1 on 2023-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0003_protocol_protocolitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="barcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="is_return",
            field=models.BooleanField(blank=True),
        ),
    ]
