# Generated by Django 4.2.1 on 2023-05-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_diagworkers_employee"),
        ("management_system", "0004_alter_protocol_barcode_alter_protocol_is_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
            ),
        ),
    ]
