# Generated by Django 4.2.1 on 2023-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0006_alter_protocol_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="employee",
        ),
    ]
