# Generated by Django 4.2.1 on 2023-05-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_diagworkers_employee"),
        ("management_system", "0009_protocolitem_protocol_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolitem",
            name="employee_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
            ),
        ),
    ]
