# Generated by Django 4.2.1 on 2023-05-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0010_protocolitem_employee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocolitem",
            name="employee_id",
        ),
    ]
