# Generated by Django 4.2.1 on 2023-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_system",
            "0013_alter_protocol_created_alter_protocol_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_it",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numer IT"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_kk",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numer KK"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=200, verbose_name="Nazwa Przedmiotu"),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_sn",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Numer S/N"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="barcode",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
