# Generated by Django 4.2.1 on 2023-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0014_alter_item_item_it_alter_item_item_kk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="barcode_img",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="is_return",
            field=models.BooleanField(blank=True, verbose_name="Zwrot"),
        ),
    ]
