# Generated by Django 4.2.1 on 2023-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0015_protocol_barcode_img_alter_protocol_is_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="barcode_img",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
