# Generated by Django 4.2.1 on 2023-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0016_alter_protocol_barcode_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="barcode_code",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
