# Generated by Django 4.2.1 on 2023-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0017_protocol_barcode_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="barcode",
        ),
        migrations.AlterField(
            model_name="protocol",
            name="barcode_img",
            field=models.ImageField(blank=True, upload_to="barcodes/"),
        ),
    ]
