# Generated by Django 4.2.1 on 2023-05-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_system",
            "0018_remove_protocol_barcode_alter_protocol_barcode_img",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="protocol",
            old_name="barcode_code",
            new_name="barcode",
        ),
    ]
