# Generated by Django 4.2.1 on 2023-05-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_employee_user_department_and_more"),
        ("management_system", "0020_alter_protocol_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.employee",
                verbose_name="Pracownik",
            ),
        ),
    ]
