# Generated by Django 4.2.1 on 2023-05-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_employee_user_department_and_more"),
        ("management_system", "0021_item_item_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200, verbose_name="Typ")),
            ],
        ),
        migrations.AlterField(
            model_name="item",
            name="item_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.employee",
                verbose_name="Pracownik",
            ),
        ),
    ]
