# Generated by Django 4.2.1 on 2023-05-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0022_itemcategory_alter_item_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management_system.itemcategory",
                verbose_name="Kategoria",
            ),
        ),
    ]
