# Generated by Django 4.2.1 on 2023-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0023_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_model",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Producent"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_producent",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Producent"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nazwa Przedmiotu"
            ),
        ),
    ]
