# Generated by Django 4.2.1 on 2023-06-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0026_protocol_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="barcode_img",
        ),
    ]
