# Generated by Django 4.2.1 on 2023-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0027_remove_protocol_barcode_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="is_scanned",
            field=models.BooleanField(default=False, verbose_name="Skan"),
        ),
    ]
