# Generated by Django 4.2.1 on 2023-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_system",
            "0029_alter_item_item_model_alter_item_item_producent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="barcode",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
