# Generated by Django 4.2.1 on 2024-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0030_alter_protocol_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="protocol_scan",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="SkanProtokolu"
            ),
        ),
    ]
