# Generated by Django 4.2.1 on 2024-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0031_protocol_protocol_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="description2",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Opis2"
            ),
        ),
    ]
