# Generated by Django 4.2.1 on 2024-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0032_protocol_description2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="description2",
        ),
        migrations.AlterField(
            model_name="protocol",
            name="protocol_scan",
            field=models.BinaryField(
                blank=True, editable=True, null=True, verbose_name="SkanProtokolu"
            ),
        ),
    ]
