# Generated by Django 4.2.1 on 2024-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0033_remove_protocol_description2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="printed_count",
            field=models.IntegerField(blank=True, default=0, verbose_name="Druk"),
        ),
    ]
