# Generated by Django 4.2.1 on 2024-05-10 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management_system", "0034_protocol_printed_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data utworzenia"),
                ),
                (
                    "utilization_company",
                    models.CharField(max_length=200, verbose_name="Firma utylizujaca"),
                ),
                (
                    "inform_dzm",
                    models.BooleanField(default=False, verbose_name="Ponfirmowano DZM"),
                ),
                (
                    "utilization_protocol_scan",
                    models.BinaryField(
                        blank=True,
                        editable=True,
                        null=True,
                        verbose_name="Skan protokolu utylizacji",
                    ),
                ),
                (
                    "company_transfer_date",
                    models.DateField(
                        auto_now=True,
                        null=True,
                        verbose_name="Data przekazania firmie zewnetrznej",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="utilization_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management_system.utilization",
                verbose_name="Utylizacja",
            ),
        ),
    ]
