# Generated by Django 4.2.1 on 2024-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0035_utilization_item_utilization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilization",
            name="company_transfer_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data przekazania firmie zewnetrznej",
            ),
        ),
        migrations.AlterField(
            model_name="utilization",
            name="utilization_company",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Firma utylizujaca"
            ),
        ),
        migrations.AlterField(
            model_name="utilization",
            name="utilization_protocol_scan",
            field=models.BinaryField(
                blank=True,
                default=None,
                editable=True,
                null=True,
                verbose_name="Skan protokolu utylizacji",
            ),
        ),
    ]
