# Generated by Django 4.2.1 on 2024-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0036_alter_utilization_company_transfer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Data modyfikacji"
            ),
        ),
    ]
