# Generated by Django 4.2.13 on 2024-05-21 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0038_alter_protocol_created_alter_protocol_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data utworzenia",
            ),
            preserve_default=False,
        ),
    ]
