# Generated by Django 4.2.13 on 2024-05-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_employee_user_email_alter_employee_user_login"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("management_system", "0040_alter_item_item_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.employee",
                verbose_name="Pracownik",
            ),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("east", "East"),
                            ("west", "West"),
                            ("north", "North"),
                            ("south", "South"),
                        ],
                        max_length=10,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
