# Generated by Django 4.2.13 on 2024-05-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("management_system", "0043_userregion_delete_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Region",
            new_name="RegionContent",
        ),
    ]
