# Generated by Django 4.2.13 on 2024-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management_system",
            "0045_remove_userregion_function_userregion_region_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regioncontent",
            name="name",
        ),
        migrations.AddField(
            model_name="regioncontent",
            name="region",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Południowy"), (2, "Północny")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="userregion",
            name="region",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Południowy"), (2, "Północny")], null=True
            ),
        ),
    ]
