# Generated by Django 4.2.13 on 2024-05-25 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "management_system",
            "0046_remove_regioncontent_name_regioncontent_region_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRegion",
            new_name="UserInfo",
        ),
    ]
