# Generated by Django 4.2.13 on 2024-05-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0047_rename_userregion_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200, verbose_name="Typ")),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management_system.region",
                verbose_name="Region",
            ),
        ),
    ]
