# Generated by Django 4.2.13 on 2024-05-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0048_region_alter_userinfo_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="region",
            old_name="category_name",
            new_name="name",
        ),
    ]
