# Generated by Django 4.2.13 on 2024-05-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0052_alter_userinfo_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regioncontent",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management_system.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management_system.region",
                verbose_name="region",
            ),
        ),
    ]
