# Generated by Django 4.2.13 on 2024-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0053_alter_regioncontent_region_alter_userinfo_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regioncontent",
            name="region",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Południowy"), (2, "Północny")], null=True
            ),
        ),
    ]
