# Generated by Django 4.2.13 on 2024-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0054_alter_regioncontent_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="editable",
            field=models.BooleanField(default=True, verbose_name="Edytowalny"),
        ),
    ]
