# Generated by Django 4.2.1 on 2023-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_employee_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user_email",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nazwisko Pracownika"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user_login",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Imię Pracownika"
            ),
        ),
    ]
