# Generated by Django 4.2.1 on 2023-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_employee_user_email_employee_user_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user_email",
            field=models.CharField(blank=True, max_length=200, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user_login",
            field=models.CharField(blank=True, max_length=200, verbose_name="Login"),
        ),
    ]
